apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: sntbiv06h-python 
  janus-idp.io/tekton: sntbiv06h-python
  backstage.io/kubernetes-id: sntbiv06h-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sntbiv06h-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml